### ISSUE TITLE
Python script failed on Ubuntu 18.04

### ISSUE THREAD

**Issue by danielz02** [Kotlin/kotlin-numpy#12]
I'm using conda environment on Ubuntu 18.04 to run the example in the README doc.
```
Exception in thread "main" java.lang.Exception: "ERROR: Command errored out with exit status 1:
     command: /home/danielz/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fx7b0ui_/ktnumpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fx7b0ui_/ktnumpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-fx7b0ui_/ktnumpy/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fx7b0ui_/ktnumpy/setup.py", line 67, in <module>
        include_dirs=get_java_includes() + ['src/main/ktnumpy/jni/include', get_numpy_include()]
      File "/tmp/pip-install-fx7b0ui_/ktnumpy/buildScr/python/utils.py", line 76, in get_java_includes
        java_include = os.path.join(java_home, 'include')
      File "/home/danielz/anaconda3/lib/python3.7/posixpath.py", line 80, in join
        a = os.fspath(a)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output." when executing the command: python -m pip install -i https://pypi.org/simple/ ktnumpy==0.1.4
	at org.jetbrains.numkt.LibraryLoader.execCommand(NativeLibUtils.kt:138)
	at org.jetbrains.numkt.LibraryLoader.loadLibraries(NativeLibUtils.kt:94)
	at org.jetbrains.numkt.Interpreter.initialize(Interpreter.kt:49)
	at org.jetbrains.numkt.Interpreter.access$initialize(Interpreter.kt:23)
	at org.jetbrains.numkt.Interpreter$Companion.getInterpreter(Interpreter.kt:30)
	at org.jetbrains.numkt.UtilsKt.callFunc(Utils.kt:59)
	at org.jetbrains.numkt.UtilsKt.callFunc$default(Utils.kt:57)
	at MainKt.main(Main.kt:38)
	at MainKt.main(Main.kt)
```

**Comment by danielz02** [comment]
Never mind I forgot to put JAVA_HOME in my PATH.
